// Central registry for all 100+ components
export const COMPONENT_LIBRARY = {
  // Layout Components (25)
  container: { name: "Container", category: "layout", icon: "📦" },
  grid: { name: "Grid System", category: "layout", icon: "🔳" },
  flexbox: { name: "Flex Container", category: "layout", icon: "📐" },
  section: { name: "Section", category: "layout", icon: "📄" },
  columns: { name: "Columns", category: "layout", icon: "🗂️" },
  sidebar: { name: "Sidebar", category: "layout", icon: "📌" },
  wrapper: { name: "Wrapper", category: "layout", icon: "🎁" },
  divider: { name: "Divider", category: "layout", icon: "➖" },
  spacer: { name: "Spacer", category: "layout", icon: "␣" },
  overlay: { name: "Overlay", category: "layout", icon: "🖼️" },
  stack: { name: "Stack", category: "layout", icon: "📚" },
  cluster: { name: "Cluster", category: "layout", icon: "🔗" },
  center: { name: "Center", category: "layout", icon: "🎯" },
  cover: { name: "Cover", category: "layout", icon: "🛡️" },
  frame: { name: "Frame", category: "layout", icon: "🖼️" },
  aspectRatio: { name: "Aspect Ratio", category: "layout", icon: "📐" },
  split: { name: "Split View", category: "layout", icon: "🔪" },
  masonry: { name: "Masonry Grid", category: "layout", icon: "🧱" },
  sticky: { name: "Sticky", category: "layout", icon: "📌" },
  fixed: { name: "Fixed Position", category: "layout", icon: "📍" },
  absolute: { name: "Absolute Position", category: "layout", icon: "🎯" },
  relative: { name: "Relative Position", category: "layout", icon: "⚓" },
  zStack: { name: "Z-Stack", category: "layout", icon: "🔄" },
  gridLines: { name: "Grid Lines", category: "layout", icon: "📏" },
  responsiveContainer: {
    name: "Responsive Container",
    category: "layout",
    icon: "📱💻",
  },

  // Typography Components (20)
  heading1: { name: "Heading 1", category: "typography", icon: "H1" },
  heading2: { name: "Heading 2", category: "typography", icon: "H2" },
  heading3: { name: "Heading 3", category: "typography", icon: "H3" },
  paragraph: { name: "Paragraph", category: "typography", icon: "📝" },
  richText: { name: "Rich Text", category: "typography", icon: "✏️" },
  quote: { name: "Quote", category: "typography", icon: "❝" },
  list: { name: "List", category: "typography", icon: "📋" },
  numberedList: { name: "Numbered List", category: "typography", icon: "🔢" },
  inlineText: { name: "Inline Text", category: "typography", icon: "📄" },
  textSpan: { name: "Text Span", category: "typography", icon: "🔤" },
  codeBlock: { name: "Code Block", category: "typography", icon: "💻" },
  label: { name: "Label", category: "typography", icon: "🏷️" },
  caption: { name: "Caption", category: "typography", icon: "📸" },
  badge: { name: "Badge", category: "typography", icon: "🪙" },
  pill: { name: "Pill", category: "typography", icon: "💊" },
  textLink: { name: "Text Link", category: "typography", icon: "🔗" },
  textBlock: { name: "Text Block", category: "typography", icon: "📄" },
  textColumn: { name: "Text Column", category: "typography", icon: "📰" },
  marquee: { name: "Marquee", category: "typography", icon: "🏃" },
  typewriter: { name: "Typewriter", category: "typography", icon: "⌨️" },

  // Navigation Components (10)
  megaMenu: { name: "Mega Menu", category: "navigation", icon: "🍔" },
  breadcrumb: { name: "Breadcrumb", category: "navigation", icon: "🍞" },
  pagination: { name: "Pagination", category: "navigation", icon: "🔢" },
  steps: { name: "Steps", category: "navigation", icon: "👣" },
  tabs: { name: "Tabs", category: "navigation", icon: "🗂️" },
  accordionNav: { name: "Accordion Nav", category: "navigation", icon: "📑" },
  sidebarNav: {
    name: "Sidebar Navigation",
    category: "navigation",
    icon: "📌",
  },
  dotNav: { name: "Dot Navigation", category: "navigation", icon: "🔘" },
  progressNav: {
    name: "Progress Navigation",
    category: "navigation",
    icon: "📊",
  },
  dropdownNav: {
    name: "Dropdown Navigation",
    category: "navigation",
    icon: "▾",
  },

  // Form Components (15)
  multiSelect: { name: "Multi Select", category: "form", icon: "☑️" },
  datePicker: { name: "Date Picker", category: "form", icon: "📅" },
  rangeSlider: { name: "Range Slider", category: "form", icon: "🎚️" },
  toggleSwitch: { name: "Toggle Switch", category: "form", icon: "🔘" },
  rating: { name: "Rating", category: "form", icon: "⭐" },
  fileUpload: { name: "File Upload", category: "form", icon: "📁" },
  colorPicker: { name: "Color Picker", category: "form", icon: "🎨" },
  searchInput: { name: "Search Input", category: "form", icon: "🔍" },
  autocomplete: { name: "Autocomplete", category: "form", icon: "🔤" },
  passwordInput: { name: "Password Input", category: "form", icon: "🔒" },
  phoneInput: { name: "Phone Input", category: "form", icon: "📱" },
  timePicker: { name: "Time Picker", category: "form", icon: "⏰" },
  richTextEditor: { name: "Rich Text Editor", category: "form", icon: "✍️" },
  signaturePad: { name: "Signature Pad", category: "form", icon: "✒️" },
  formStepper: { name: "Form Stepper", category: "form", icon: "🔄" },

  // Data Display Components (15)
  dataTable: { name: "Data Table", category: "data", icon: "📊" },
  timeline: { name: "Timeline", category: "data", icon: "⏳" },
  progress: { name: "Progress", category: "data", icon: "📈" },
  statsCard: { name: "Stats Card", category: "data", icon: "📊" },
  chart: { name: "Chart", category: "data", icon: "📈" },
  calendar: { name: "Calendar", category: "data", icon: "📆" },
  treeView: { name: "Tree View", category: "data", icon: "🌳" },
  kanbanBoard: { name: "Kanban Board", category: "data", icon: "📋" },
  listGroup: { name: "List Group", category: "data", icon: "📋" },
  cardGrid: { name: "Card Grid", category: "data", icon: "🃏" },
  badgeList: { name: "Badge List", category: "data", icon: "🪙" },
  avatarGroup: { name: "Avatar Group", category: "data", icon: "👥" },
  tagCloud: { name: "Tag Cloud", category: "data", icon: "☁️" },
  metricDisplay: { name: "Metric Display", category: "data", icon: "📏" },
  comparisonTable: { name: "Comparison Table", category: "data", icon: "⚖️" },

  // Feedback Components (8)
  toast: { name: "Toast", category: "feedback", icon: "🍞" },
  tooltip: { name: "Tooltip", category: "feedback", icon: "💡" },
  spinner: { name: "Spinner", category: "feedback", icon: "🌀" },
  skeleton: { name: "Skeleton", category: "feedback", icon: "💀" },
  alert: { name: "Alert", category: "feedback", icon: "⚠️" },
  notification: { name: "Notification", category: "feedback", icon: "🔔" },
  progressRing: { name: "Progress Ring", category: "feedback", icon: "⭕" },
  statusIndicator: {
    name: "Status Indicator",
    category: "feedback",
    icon: "🟢",
  },

  // Overlay Components (7)
  dropdown: { name: "Dropdown", category: "overlay", icon: "▾" },
  popover: { name: "Popover", category: "overlay", icon: "💭" },
  drawer: { name: "Drawer", category: "overlay", icon: "🗄️" },
  lightbox: { name: "Lightbox", category: "overlay", icon: "🔍" },
  contextMenu: { name: "Context Menu", category: "overlay", icon: "☰" },
  modal: { name: "Modal", category: "overlay", icon: "📦" },
  tooltipWrapper: { name: "Tooltip Wrapper", category: "overlay", icon: "💡" },

  // Media Components (10)
  gallery: { name: "Gallery", category: "media", icon: "🖼️" },
  videoPlayer: { name: "Video Player", category: "media", icon: "🎬" },
  carousel: { name: "Carousel", category: "media", icon: "🎠" },
  imageSlider: { name: "Image Slider", category: "media", icon: "🖼️" },
  audioPlayer: { name: "Audio Player", category: "media", icon: "🎵" },
  imageComparison: { name: "Image Comparison", category: "media", icon: "🔄" },
  parallaxImage: { name: "Parallax Image", category: "media", icon: "🌄" },
  videoBackground: { name: "Video Background", category: "media", icon: "🎥" },
  mediaGrid: { name: "Media Grid", category: "media", icon: "🔳" },
  lazyImage: { name: "Lazy Image", category: "media", icon: "🖼️" },
} as const;
