import type { Project } from "@/state/useCanvasStore";
import type { Element } from "@/state/useDesignStore";
import { generateExport } from "@/utils/exportGenerators";

type DesignElements = Record<string, Element>;

interface FileRecord {
  name: string;
  content: string;
}

export function generateNextJsProject(
  project: Project,
  designElements: DesignElements
): FileRecord[] {
  const pageContent = generateExport(
    project,
    "react-tailwind",
    designElements
  ).code;

  return [
    {
      name: "package.json",
      content: JSON.stringify(
        {
          name: "polyglot-export",
          version: "0.1.0",
          private: true,
          scripts: {
            dev: "next dev",
            build: "next build",
            start: "next start",
            lint: "next lint",
          },
          dependencies: {
            react: "^19.0.0",
            "react-dom": "^19.0.0",
            next: "16.0.10",
          },
          devDependencies: {
            typescript: "^5",
            "@types/node": "^20",
            "@types/react": "^19",
            "@types/react-dom": "^19",
            postcss: "^8",
            tailwindcss: "^4.1.18",
            eslint: "^9",
            "eslint-config-next": "16.0.10",
          },
        },
        null,
        2
      ),
    },
    {
      name: "src/app/page.tsx",
      content: pageContent,
    },
    {
      name: "src/app/layout.tsx",
      content: `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "${project.name}",
  description: "Generated by Polyglot",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`,
    },
    {
      name: "src/app/globals.css",
      content: `@import "tailwindcss";

body {
  margin: 0;
}
`,
    },
  ];
}
