import React from "react";
import { useAgentStore } from "@/state/useAgentStore";

export default function AgentArtifact({ artifactId }: { artifactId: string }) {
  // Skeleton renderer for rich UI elements generated by the agent.
  // In production, this would parse a markdown artifact or mount interactive React nodes.
  
  return (
    <div className="p-4 mt-2 border border-[var(--border-subtle)] bg-[var(--bg-surface)] rounded-xl shadow-md">
      <div className="flex items-center gap-2 mb-2">
        <div className="w-2 h-2 rounded-full bg-violet-500 animate-pulse" />
        <span className="text-xs font-bold text-violet-400">Interactive Artifact</span>
      </div>
      <p className="text-xs text-[var(--text-muted)]">
        Artifact {artifactId} rendered here.
      </p>
    </div>
  );
}
